name: Logistics API Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t zacharyeck/logistics-logistics-api:latest .
        docker push zacharyeck/logistics-logistics-api:latest

  deploy-helm:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Set up kind
      uses: helm/kind-action@v1

    - name: Build Docker image
      run: |
        docker build -t logistics-api:latest .

    - name: Load image into kind
      run: |
        kind load docker-image logistics-api:latest --name chart-testing

    - name: Deploy via Helm
      run: |
        helm upgrade --install logistics-api ./charts/logistics-api -f ./charts/logistics-api/values.yaml

    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/logistics-api -n default
        kubectl get pods -n default